[
    {
        "dispatch":"中国",
        "goods":
        [
            {
                "itemID":"301",
                "itemCount":5
            },
            {
                "itemID":"304",
                "itemCount":1
            },
            {
                "itemID":"321",
                "itemCount":3
            }
        ]
    },
    {
        "dispatch":"德国",
        "goods":
        [
            {
                "itemID":"401",
                "itemCount":5
            },
            {
                "itemID":"404",
                "itemCount":1
            },
            {
                "itemID":"421",
                "itemCount":3
            }
         ]
    },
    {
        "dispatch":"日本",
        "goods":
        [
            {
                "itemID":"501",
                "itemCount":5
            },
            {
                "itemID":"504",
                "itemCount":1
            },
            {
                "itemID":"521",
                "itemCount":3
            }
        ]
    }
]